services:
  db:
    image: pgvector/pgvector:pg16 # Uses an image with PostgreSQL 16 and pgvector pre-installed
    container_name: beautybase_db
    restart: always
    ports:
      - "5432:5432" # Exposes PostgreSQL port to our host machine
    volumes:
      - beautybase_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=beautybase_user
      - POSTGRES_PASSWORD=Hansi@1966
      - POSTGRES_DB=beautybase_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beautybase_user -d beautybase_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  beautybase_postgres_data: # Defines a Docker volume to persist data
